name: NDK build

on:
  push:
  pull_request:

jobs:
  build:
    env:
      module_id: mimalloc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: recursive
          lfs: true
      - name: Install Powershell
        run: sudo apt-get install -y powershell

      - name: Setup NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1.0.3
        with:
          ndk-version: r22

      - name: Create ndkpath.txt
        run: echo ${{ steps.setup-ndk.outputs.ndk-path }} > ${GITHUB_WORKSPACE}/ndkpath.txt

      #     - name: Cache QPM
      #       id: cache-qpm
      #       uses: actions/cache@v2
      #       env:
      #         cache-name: cache-qpm
      #       with:
      #         path: QPM
      #         key: ${{ runner.os }}-${{ env.cache-name }}-2
      #         restore-keys: |
      #           ${{ runner.os }}-${{ env.cache-name }}-2

      - name: Get QPM
        if: steps.cache-qpm.outputs.cache-hit != 'true'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          name: QPM-ubuntu-x64
          path: QPM
          repo: sc2ad/QuestPackageManager

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}
          chmod +x ./build.sh
          ./build.sh
      - name: Get Library Name
        id: libname
        run: |
          pattern="lib${module_id}*.a"
          files=( $pattern )
          echo ::set-output name=NAME::"${files[0]}"
      - name: Upload debug artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug_${{ steps.libname.outputs.NAME }}
          path: ./${{ steps.libname.outputs.NAME }}
          if-no-files-found: error
    # TODO: Add auto-populating releases, auto update versions, auto publish package on release
